project = 'StarWave'
author = 'StarWave contributors'
copyright = '2026, StarWave contributors'
version = '2.0'
release = '2.0.0'
language = 'zh_CN'
extensions = ['myst_parser', 'sphinx.ext.githubpages']
source_suffix = {'.md': 'markdown'}
root_doc = 'index'
exclude_patterns = ['requirements.txt', '_build', 'Thumbs.db', '.DS_Store']
myst_enable_extensions = ['colon_fence']
myst_heading_anchors = 3
nitpicky = True
html_theme = 'sphinx_rtd_theme'
html_theme_options = {'collapse_navigation': False, 'navigation_depth': 3, 'style_nav_header_background': '#17354c'}
html_static_path = ['_static']
html_css_files = ['custom.css']
html_title = 'StarWave 2.0.0 使用手册（草稿）'
html_show_sourcelink = False
html_copy_source = False
html_show_sphinx = True
html_last_updated_fmt = None
